version: '3'

tasks:
  run:
    cmds:
      - go run ./cmd/runner/main.go -config=./config/local.yml
  migrate:run:
    desc: Запуск миграций
    cmds:
      - go run ./cmd/migrate/run/pg/main.go -config=./config/local.yml