// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: conv-pdf-service.proto

package convpdf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConvertatingToPdf_ConvertingToPdf_FullMethodName = "/convpdf.ConvertatingToPdf/ConvertingToPdf"
)

// ConvertatingToPdfClient is the client API for ConvertatingToPdf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConvertatingToPdfClient interface {
	ConvertingToPdf(ctx context.Context, in *ConvertatingToPdfRequest, opts ...grpc.CallOption) (*ConvertatingtoPdfResponse, error)
}

type convertatingToPdfClient struct {
	cc grpc.ClientConnInterface
}

func NewConvertatingToPdfClient(cc grpc.ClientConnInterface) ConvertatingToPdfClient {
	return &convertatingToPdfClient{cc}
}

func (c *convertatingToPdfClient) ConvertingToPdf(ctx context.Context, in *ConvertatingToPdfRequest, opts ...grpc.CallOption) (*ConvertatingtoPdfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertatingtoPdfResponse)
	err := c.cc.Invoke(ctx, ConvertatingToPdf_ConvertingToPdf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConvertatingToPdfServer is the server API for ConvertatingToPdf service.
// All implementations must embed UnimplementedConvertatingToPdfServer
// for forward compatibility.
type ConvertatingToPdfServer interface {
	ConvertingToPdf(context.Context, *ConvertatingToPdfRequest) (*ConvertatingtoPdfResponse, error)
	mustEmbedUnimplementedConvertatingToPdfServer()
}

// UnimplementedConvertatingToPdfServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConvertatingToPdfServer struct{}

func (UnimplementedConvertatingToPdfServer) ConvertingToPdf(context.Context, *ConvertatingToPdfRequest) (*ConvertatingtoPdfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertingToPdf not implemented")
}
func (UnimplementedConvertatingToPdfServer) mustEmbedUnimplementedConvertatingToPdfServer() {}
func (UnimplementedConvertatingToPdfServer) testEmbeddedByValue()                           {}

// UnsafeConvertatingToPdfServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConvertatingToPdfServer will
// result in compilation errors.
type UnsafeConvertatingToPdfServer interface {
	mustEmbedUnimplementedConvertatingToPdfServer()
}

func RegisterConvertatingToPdfServer(s grpc.ServiceRegistrar, srv ConvertatingToPdfServer) {
	// If the following call pancis, it indicates UnimplementedConvertatingToPdfServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConvertatingToPdf_ServiceDesc, srv)
}

func _ConvertatingToPdf_ConvertingToPdf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertatingToPdfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConvertatingToPdfServer).ConvertingToPdf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConvertatingToPdf_ConvertingToPdf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConvertatingToPdfServer).ConvertingToPdf(ctx, req.(*ConvertatingToPdfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConvertatingToPdf_ServiceDesc is the grpc.ServiceDesc for ConvertatingToPdf service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConvertatingToPdf_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "convpdf.ConvertatingToPdf",
	HandlerType: (*ConvertatingToPdfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertingToPdf",
			Handler:    _ConvertatingToPdf_ConvertingToPdf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conv-pdf-service.proto",
}
