// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: doc-gen.proto

package docgen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentGenerator_GenerateDocument_FullMethodName = "/docgen.DocumentGenerator/GenerateDocument"
)

// DocumentGeneratorClient is the client API for DocumentGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentGeneratorClient interface {
	GenerateDocument(ctx context.Context, in *GenerateDocRequest, opts ...grpc.CallOption) (*GenerateDocResponse, error)
}

type documentGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentGeneratorClient(cc grpc.ClientConnInterface) DocumentGeneratorClient {
	return &documentGeneratorClient{cc}
}

func (c *documentGeneratorClient) GenerateDocument(ctx context.Context, in *GenerateDocRequest, opts ...grpc.CallOption) (*GenerateDocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDocResponse)
	err := c.cc.Invoke(ctx, DocumentGenerator_GenerateDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentGeneratorServer is the server API for DocumentGenerator service.
// All implementations must embed UnimplementedDocumentGeneratorServer
// for forward compatibility.
type DocumentGeneratorServer interface {
	GenerateDocument(context.Context, *GenerateDocRequest) (*GenerateDocResponse, error)
	mustEmbedUnimplementedDocumentGeneratorServer()
}

// UnimplementedDocumentGeneratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentGeneratorServer struct{}

func (UnimplementedDocumentGeneratorServer) GenerateDocument(context.Context, *GenerateDocRequest) (*GenerateDocResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDocument not implemented")
}
func (UnimplementedDocumentGeneratorServer) mustEmbedUnimplementedDocumentGeneratorServer() {}
func (UnimplementedDocumentGeneratorServer) testEmbeddedByValue()                           {}

// UnsafeDocumentGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentGeneratorServer will
// result in compilation errors.
type UnsafeDocumentGeneratorServer interface {
	mustEmbedUnimplementedDocumentGeneratorServer()
}

func RegisterDocumentGeneratorServer(s grpc.ServiceRegistrar, srv DocumentGeneratorServer) {
	// If the following call pancis, it indicates UnimplementedDocumentGeneratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentGenerator_ServiceDesc, srv)
}

func _DocumentGenerator_GenerateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentGeneratorServer).GenerateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentGenerator_GenerateDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentGeneratorServer).GenerateDocument(ctx, req.(*GenerateDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentGenerator_ServiceDesc is the grpc.ServiceDesc for DocumentGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docgen.DocumentGenerator",
	HandlerType: (*DocumentGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateDocument",
			Handler:    _DocumentGenerator_GenerateDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doc-gen.proto",
}
