// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: doc-gen.proto

package docgen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserDataJson  string                 `protobuf:"bytes,1,opt,name=user_data_json,json=userDataJson,proto3" json:"user_data_json,omitempty"`
	DocUrl        string                 `protobuf:"bytes,2,opt,name=doc_url,json=docUrl,proto3" json:"doc_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDocRequest) Reset() {
	*x = GenerateDocRequest{}
	mi := &file_doc_gen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDocRequest) ProtoMessage() {}

func (x *GenerateDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doc_gen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDocRequest.ProtoReflect.Descriptor instead.
func (*GenerateDocRequest) Descriptor() ([]byte, []int) {
	return file_doc_gen_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateDocRequest) GetUserDataJson() string {
	if x != nil {
		return x.UserDataJson
	}
	return ""
}

func (x *GenerateDocRequest) GetDocUrl() string {
	if x != nil {
		return x.DocUrl
	}
	return ""
}

type GenerateDocResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoneDocPath   string                 `protobuf:"bytes,1,opt,name=done_doc_path,json=doneDocPath,proto3" json:"done_doc_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDocResponse) Reset() {
	*x = GenerateDocResponse{}
	mi := &file_doc_gen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDocResponse) ProtoMessage() {}

func (x *GenerateDocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doc_gen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDocResponse.ProtoReflect.Descriptor instead.
func (*GenerateDocResponse) Descriptor() ([]byte, []int) {
	return file_doc_gen_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateDocResponse) GetDoneDocPath() string {
	if x != nil {
		return x.DoneDocPath
	}
	return ""
}

var File_doc_gen_proto protoreflect.FileDescriptor

const file_doc_gen_proto_rawDesc = "" +
	"\n" +
	"\rdoc-gen.proto\x12\x06docgen\"S\n" +
	"\x12GenerateDocRequest\x12$\n" +
	"\x0euser_data_json\x18\x01 \x01(\tR\fuserDataJson\x12\x17\n" +
	"\adoc_url\x18\x02 \x01(\tR\x06docUrl\"9\n" +
	"\x13GenerateDocResponse\x12\"\n" +
	"\rdone_doc_path\x18\x01 \x01(\tR\vdoneDocPath2`\n" +
	"\x11DocumentGenerator\x12K\n" +
	"\x10GenerateDocument\x12\x1a.docgen.GenerateDocRequest\x1a\x1b.docgen.GenerateDocResponseB\vZ\t./;docgenb\x06proto3"

var (
	file_doc_gen_proto_rawDescOnce sync.Once
	file_doc_gen_proto_rawDescData []byte
)

func file_doc_gen_proto_rawDescGZIP() []byte {
	file_doc_gen_proto_rawDescOnce.Do(func() {
		file_doc_gen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_doc_gen_proto_rawDesc), len(file_doc_gen_proto_rawDesc)))
	})
	return file_doc_gen_proto_rawDescData
}

var file_doc_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_doc_gen_proto_goTypes = []any{
	(*GenerateDocRequest)(nil),  // 0: docgen.GenerateDocRequest
	(*GenerateDocResponse)(nil), // 1: docgen.GenerateDocResponse
}
var file_doc_gen_proto_depIdxs = []int32{
	0, // 0: docgen.DocumentGenerator.GenerateDocument:input_type -> docgen.GenerateDocRequest
	1, // 1: docgen.DocumentGenerator.GenerateDocument:output_type -> docgen.GenerateDocResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_doc_gen_proto_init() }
func file_doc_gen_proto_init() {
	if File_doc_gen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_doc_gen_proto_rawDesc), len(file_doc_gen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_doc_gen_proto_goTypes,
		DependencyIndexes: file_doc_gen_proto_depIdxs,
		MessageInfos:      file_doc_gen_proto_msgTypes,
	}.Build()
	File_doc_gen_proto = out.File
	file_doc_gen_proto_goTypes = nil
	file_doc_gen_proto_depIdxs = nil
}
